name: Build and deploy

on:
  push:
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        run: pnpm run build:pwa

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        env:
          VITE_TMDB_READ_API_KEY: ${{ secrets.TMDB_READ_API_KEY }}
          VITE_CORS_PROXY_URL: ${{ secrets.CORS_PROXY_URL }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '3'
          command: pages deploy dist/ --project-name=movie-web
